MTD/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MTD.Helpers;
using MTD.DAL;
using MTD.Models;
using MTD.Services;

namespace MTD.Controllers
{
    public class BaseController : Controller
    {
        public BaseController()
        {
            
        }

        // Phân trang.
        public void Paging(int page, int pageSize, int totalRecord)
        {
            ViewBag.page = page;
            ViewBag.pageSize = pageSize;

            ViewBag.MaxPage = (int)Math.Ceiling((double)totalRecord / pageSize);
            ViewBag.PageShow = 5;
            ViewBag.PagePreview = 2;
            ViewBag.TotalRecord = totalRecord;
        }

        /// <summary> Kiểm tra xem tài khoản có phải là Admin hay không.
        /// </summary>
        /// <returns></returns>
        public bool IsAdmin()
        {
            int accId = 0; // AccountID
            int.TryParse(CookieHelper.Get(Configs.COOKIES_ACCOUNT_ID), out accId);
            try
            {
                // Nếu tài khoản đã là Admin thì cần kiểm tra thêm xem quyền đó còn được hoạt động hay không.
                if (CookieHelper.Get(Configs.COOKIES_ADMIN) == "1")
                {
                    AccountService service = new AccountService();
                    return service.IsAdmin(accId);
                }
                return false;
            }
            catch
            {
                return false;
            }
            
        }

        /// <summary>Lấy thông báo lỗi.
        /// </summary>
        /// <param name="errorKey"></param>
        /// <returns></returns>
        public string GetErrorMessage(int errorKey)
        {
            string result = "";
            switch (errorKey)
            {
                case -1:

                    break;

                case -404:
                    result = Configs.ERROR_NOT_FOUND_ACCOUNT;
                    break;
                default:
                    result = Configs.ERROR_PROCESS;
                    break;
            }
            return result;
        }

        /// <summary>Set template data sử dụng cho toàn web.
        /// </summary>
        /// <param name="message"></param>
        public void SetTempData(string message)
        {
            TempData[Configs.TEMP_MESSAGE] = message;
            TempData[Configs.TEMP_REDIRECT] = "";
        }

        /// <summary> Set template data sử dụng cho toàn web.
        /// </summary>
        /// <param name="message"></param>
        /// <param name="redirect"></param>
        public void SetTempData(string message, string redirect)
        {
            TempData[Configs.TEMP_MESSAGE] = message;
            TempData[Configs.TEMP_REDIRECT] = redirect;
        }

        /// <summary>
        /// Xử lý chuyển tới trang chủ khi không được phép truy cập.
        /// </summary>
        public void SetRedirectNotAllow()
        {
            TempData[Configs.TEMP_MESSAGE] = Configs.ALERT_NOT_ALLOW;
            TempData[Configs.TEMP_REDIRECT] = Url.Action("Index", "Words");
        }

        public void InitAccount(AccountModel model, int dayExpires = 1)
        {
            string isAdmin = model.RoleId == 777 ? "1" : "0";
            
            CookieHelper.Set(Configs.COOKIES_USERNAME, model.UserName, dayExpires);
            CookieHelper.Set(Configs.COOKIES_ADMIN, isAdmin, dayExpires);
            CookieHelper.Set(Configs.COOKIES_ROLE_ID, model.RoleId.ToString(), dayExpires);
            CookieHelper.Set(Configs.COOKIES_ACCOUNT_ID, model.Id.ToString(), dayExpires);
        }

        public void RemoveAccount()
        {
            CookieHelper.Remove(Configs.COOKIES_USERNAME);
            CookieHelper.Remove(Configs.COOKIES_ACCOUNT_ID);
            CookieHelper.Remove(Configs.COOKIES_ADMIN);
            CookieHelper.Remove(Configs.COOKIES_ROLE_ID);
        }

        public ActionResult BoxSidebar()
        {
            ViewBag.ListDictTypeGlobal = HttpContext.Application["LIST_DICT_TYPE"];
            return PartialView("_BoxSidebar");
        }

        /// <summary>
        /// Hàm lấy danh sách place con theo id cha, trả về 1 chuỗi JSon.
        /// </summary>
        /// <param name="parentId">ID City</param>
        /// <returns>Json</returns>
        [HttpPost]
        public JsonResult ListPlaceJson(int parentId)
        {
            PlaceService placeService = new PlaceService();
            List<SelectListItem> lstEntity = placeService.ListItem(parentId);
            lstEntity.Insert(0, new SelectListItem { Value = "0", Text = "" });
            return Json(lstEntity);
        }
    }
}

MTD/Views/Shared/_BoxFooter.cshtml
<div class="footer">
    

    <div class="footer-inner">
        <div class="footer-content">
            <span class="bigger-120"><span class="blue bolder">Trang tra cứu từ điển</span> &copy; 2018
            <span class="red bigger-120">(Phiên bản thử nghiệm)</span>
            </span>
        </div>
    </div>
</div>

MTD/Views/Shared/_BoxSidebar.cshtml
@{
    int tabId = TempData["TabId"] == null ? 0 : (int)TempData["TabId"];
    List<SelectListItem> listDictType = ViewBag.ListDictTypeGlobal;
}

<div id="sidebar" class="sidebar h-sidebar navbar-collapse collapse ace-save-state">
    <ul class="nav nav-list">
        <li class="hover @(tabId == 0?"active open":"")">
            <a href="@Url.Action("Index","Words")">
                <span class="menu-text">Trang chủ </span>
            </a></li>
        @if (listDictType.Count > 0)
        {
            foreach (var item in listDictType)
            {
                <li class="hover @(tabId == int.Parse(item.Value) ? "active open" : "")">
                    <a href="@Url.Action("Index", "Words", new { @DictType = item.Value })" data-hover="dropdown" data-toggle="dropdown" class="dropdown-toggle disabled ">
                        <span class="menu-text">@item.Text</span>
                    </a>
                </li>
            }
        }
        
        <li class="hover @(tabId == 98 ? "active open" : "")"><a href="widgets.html"><span class="menu-text">Hỏi đáp </span></a></li>
        <li class="hover @(tabId == 99 ? "active open" : "")"><a href="widgets.html"><span class="menu-text">Liên hệ </span></a></li>
    </ul>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $(".dropdown-toggle").click(function () {
            var url = $(this).attr("href");
            $(location).attr('href', url);
        });
    }); 
</script>

MTD/Views/Shared/_BoxTopMenu.cshtml
@using MTD.Helpers
@{
    
}
<style type="text/css">
    .datepicker
    {
        z-index: 1151 !important;
    }
    .clsDatePicker {
        z-index: 100000;
    }
</style>
<div id="navbar" class="navbar navbar-default    navbar-collapse       h-navbar ace-save-state">
    <div class="navbar-container ace-save-state" id="navbar-container">
        <div class="navbar-header pull-left">
            <a href="@Url.Action("Index", "Words", new { area = "" })">
				<img src="@Url.Content("~/Assets/images/logo.png")" height="45px"alt="" />
			</a>
            <button class="pull-right navbar-toggle navbar-toggle-img collapsed" type="button"
                data-toggle="collapse" data-target=".navbar-buttons,.navbar-menu">
                <span class="sr-only">Toggle user menu</span>
                
            </button>
            <button class="pull-right navbar-toggle collapsed" type="button" data-toggle="collapse"
                data-target="#sidebar">
                <span class="sr-only">Toggle sidebar</span> <span class="icon-bar"></span><span class="icon-bar">
                </span><span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-buttons navbar-header pull-right  collapse navbar-collapse" role="navigation">
            <ul class="nav ace-nav">
                @if (CookieHelper.Get(Configs.COOKIES_ACCOUNT_ID) != null)
                {
                    <li class="light-blue dropdown-modal">
                        <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <span class="user-info"><small>Xin chào:</small> @CookieHelper.Get(Configs.COOKIES_USERNAME) </span>
                        <i class="ace-icon fa fa-caret-down"></i>
                        </a>
                        <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                            <li>
                                <a href="@Url.Action("PersonalInfo", "User", new { area="Admin"})">
				                    <i class="ace-icon fa fa-user"></i>
				                    Thông tin cá nhân
			                    </a>
		                    </li>
                            <li>
                                <a href="@Url.Action("ChangePassword", "User", new{area="Admin"})">
				                    <i class="ace-icon fa fa-key"></i>
				                    Đổi mật khẩu
			                    </a>
		                    </li>
                            <li>
                                <a href="#" id="logout" data-href="@Url.Action("DoLogout", "User")" data-toggle="modal"  data-target="#confirm-logout">
                                    <i class="ace-icon fa fa-sign-out"></i> <span>Thoát</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                }
                else
                {
                    <li>
                        <a href="@Url.Action("Registry","User")"> Đăng ký</a>
                    </li>
                    <li><a href="@Url.Action("Login","User")">Đăng nhập</a> </li>
                }
            </ul>
        </div>
        <nav role="navigation" class="navbar-menu pull-left collapse navbar-collapse">
			<ul class="nav navbar-nav">
                @if (CookieHelper.Get(Configs.COOKIES_ADMIN) == "1")
                {
                    <li>
					    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="ace-icon fa fa-user bigger-110"></i><span>Quản lý thành viên</span><i class="ace-icon fa fa-angle-down bigger-110"></i></a>
                        <ul class="dropdown-menu dropdown-light-blue dropdown-caret">
                            <li>
                                <a href="@Url.Action("ListAccount", "User")">Danh sách tài khoản</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Create", "User")">Thêm tài khoản</a>
                            </li>
                            <li>
                                <a href="@Url.Action("ListPersonal", "User")">Danh sách thành viên</a>
                            </li>
                            <li>
                                <a href="@Url.Action("PersonalInformation", "User", new { @Id=0, @AccountId = 0 })">Thêm thành viên</a>
                            </li>
                        </ul>
				    </li>
                    <li>
					    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="ace-icon fa fa-list bigger-110"></i><span>Quản lý từ điển</span><i class="ace-icon fa fa-angle-down bigger-110"></i></a>
                        <ul class="dropdown-menu dropdown-light-blue dropdown-caret">
                            <li>
                                <a href="@Url.Action("List", "Words")">Danh sách từ vựng</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Update", "Words", new {Id=0 })">Thêm từ</a>
                            </li>
                            <li>
                                <a href="#">Cập nhật từ file Excel</a>
                            </li>
                        </ul>
				    </li>
                }
                <li>
                    <a href="#" id=""><i class="ace-icon fa  bigger-110"></i><span>Lịch sử tra từ</span></a>
				</li>
			</ul>
		</nav>
    </div>
</div>
<div class="modal fade in" id="register_model">
    <div id="register-container">
    </div>
</div>
<div class="modal fade" id="confirm-logout" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Logout
            </div>
            <div class="modal-body">
                @Configs.CONFIRM_LOGOUT
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <a class="btn btn-danger btn-ok">OK</a>
            </div>
        </div>
    </div>
</div>

<script src="@Url.Content("~/Assets/js/bootstrap-datepicker.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    $('#confirm-logout').on('show.bs.modal', function (e) {
        $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
    });
</script>

MTD/Views/Shared/_Layout.cshtml
@using MTD.Helpers;
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta charset="utf-8" />
		<title>@ViewBag.Title</title>

		<meta name="description" content="top menu &amp; navigation" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

        <link rel="icon" href="@Url.Content("~/Assets/images/logo.png")">

		<!-- bootstrap & fontawesome -->
        <link href="@Url.Content("~/Assets/css/bootstrap.min.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Assets/font-awesome/4.5.0/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />
		
		<!-- page specific plugin styles -->
		<!-- text fonts -->
        <link href="@Url.Content("~/Assets/css/fonts.googleapis.com.css")" rel="stylesheet" type="text/css" />

		<!-- ace styles -->
        <link href="@Url.Content("~/Assets/css/ace.min.css")" rel="stylesheet" type="text/css" />

		<!--[if lte IE 9]>
            <link href="@Url.Content("~/Assets/css/ace-part2.min.css")" rel="stylesheet" type="text/css" />
		<![endif]-->
        @*<link href="@Url.Content("~/Assets/css/ace-skins.min.css")" rel="stylesheet" type="text/css" />*@
        <link href="@Url.Content("~/Assets/css/ace-rtl.min.css")" rel="stylesheet" type="text/css" />
        
		<!--[if lte IE 9]>
          <link href="@Url.Content("~/Assets/css/ace-ie.min.css")" rel="stylesheet" type="text/css" />
		<![endif]-->
        <link rel="stylesheet" type="text/css" href="@Url.Content("~/Assets/css/bootstrap-datetimepicker.min.css")" />
        <style type="text/css">
            .field-validation-error {
            color: #e80c4d;
            font-weight: bold;
            }

            .field-validation-valid {
                display: none;
            }

            input.input-validation-error {
                border: 1px solid #e80c4d;
            }

            input[type="checkbox"].input-validation-error {
                border: 0 none;
            }

            .validation-summary-errors {
                color: #e80c4d;
                font-weight: bold;
                font-size: 1.1em;
            }

            .validation-summary-valid {
                display: none;
            }
            th {
               text-align: center;   
            }
        </style>
		<!-- inline styles related to this page -->

        <!--[if !IE]> -->
        <script src="@Url.Content("~/Assets/js/jquery-2.1.4.min.js")" type="text/javascript"></script>

		<!-- <![endif]-->

		<!-- ace settings handler -->
        <script src="@Url.Content("~/Assets/js/ace-extra.min.js")" type="text/javascript"></script>

		<!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

		<!--[if lte IE 8]>
        <script src="@Url.Content("~/Assets/js/html5shiv.min.js")" type="text/javascript"></script>
                <script src="@Url.Content("~/Assets/js/respond.min.js")" type="text/javascript"></script>
		<![endif]-->
        @if (TempData[Configs.TEMP_MESSAGE] != null)
            {
                <div class="modal face" id="message-admin" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                Thông báo
                            </div>
                            <div class="modal-body">
                                @TempData[Configs.TEMP_MESSAGE]
                            </div>
                            <div class="modal-footer">
                                <button type="button" id="btnOK" class="btn btn-default" data-dismiss="modal">OK</button>
                            </div>
                        </div>
                    </div>
                </div>
            <script type="text/javascript">
                jQuery(document).ready(function () {
                    jQuery('#message-admin').modal("show");
                    
                    $("#btnOK").on("click",function(){
                        var urlRedirect = '@TempData[Configs.TEMP_REDIRECT]';
                        if (urlRedirect.length > 0) {
                            window.location = urlRedirect;
                        }
                    });
                });
            </script>
    
                TempData[Configs.TEMP_MESSAGE] = null;
                TempData[Configs.TEMP_REDIRECT] = null;
            }
	</head>

	<body class="skin-green">
		@Html.Partial("_BoxTopMenu")

		<div class="main-container ace-save-state" id="main-container">
			<script type="text/javascript">
			    try { ace.settings.loadState('main-container') } catch (e) { }
			</script>

            @Html.Action("BoxSidebar", "Base")

			<div class="main-content">
                @RenderSection("MainContent", required: true)

                <div class="centered col-lg-12 col-offset-12 " style="background-color:#90EE90">
                @*@Html.Action("BoxLink", "Template1", new { @Position = 1 })*@
                </div>
			</div>


			@Html.Partial("_BoxFooter")



			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		

		<!--[if IE]>
<script src="@Url.Content("~/Assets/js/jquery-1.11.3.min.js")" type="text/javascript"></script>
<![endif]-->
		<script type="text/javascript">
		    @*if ('ontouchstart' in document.documentElement) document.write("<script src=@Url.Content("~/Assets/js/jquery.mobile.custom.min.js")></script>");*@
		</script>
        <script src="@Url.Content("~/Assets/js/bootstrap.min.js")" type="text/javascript"></script>
		
		<!-- page specific plugin scripts -->

		<!-- ace scripts -->
        <script src="@Url.Content("~/Assets/js/ace-elements.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Assets/js/ace.min.js")" type="text/javascript"></script>

        
       @*<script src="@Url.Content("~/Assets/Template1/js/moment.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Assets/Template1/js/bootstrap-timepicker.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Assets/Template1/js/daterangepicker.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Assets/Template1/js/bootstrap-datetimepicker.min.js")" type="text/javascript"></script>*@
		<!-- inline scripts related to this page -->
		<script type="text/javascript">
		    jQuery(function ($) {
		        var $sidebar = $('.sidebar').eq(0);
		        if (!$sidebar.hasClass('h-sidebar')) return;

		        $(document).on('settings.ace.top_menu', function (ev, event_name, fixed) {
		            if (event_name !== 'sidebar_fixed') return;

		            var sidebar = $sidebar.get(0);
		            var $window = $(window);

		            //return if sidebar is not fixed or in mobile view mode
		            var sidebar_vars = $sidebar.ace_sidebar('vars');
		            if (!fixed || (sidebar_vars['mobile_view'] || sidebar_vars['collapsible'])) {
		                $sidebar.removeClass('lower-highlight');
		                //restore original, default marginTop
		                sidebar.style.marginTop = '';

		                $window.off('scroll.ace.top_menu')
		                return;
		            }


		            var done = false;
		            $window.on('scroll.ace.top_menu', function (e) {

		                var scroll = $window.scrollTop();
		                scroll = parseInt(scroll / 4); //move the menu up 1px for every 4px of document scrolling
		                if (scroll > 17) scroll = 17;


		                if (scroll > 16) {
		                    if (!done) {
		                        $sidebar.addClass('lower-highlight');
		                        done = true;
		                    }
		                }
		                else {
		                    if (done) {
		                        $sidebar.removeClass('lower-highlight');
		                        done = false;
		                    }
		                }

		                sidebar.style['marginTop'] = (17 - scroll) + 'px';
		            }).triggerHandler('scroll.ace.top_menu');

		        }).triggerHandler('settings.ace.top_menu', ['sidebar_fixed', $sidebar.hasClass('sidebar-fixed')]);

		        $(window).on('resize.ace.top_menu', function () {
		            $(document).triggerHandler('settings.ace.top_menu', ['sidebar_fixed', $sidebar.hasClass('sidebar-fixed')]);
		        });
		    });
		    function updateFollow(btn) {
		        var productId = btn.replace('btnFollow_', '');
		        jQuery.ajax({
		            type: 'POST',
		            async: false,
		            cache: false,
		            url: '@Url.Action("UpdateProductFollow", "Product")',
		            contentType: "application/json; charset=utf-8",
		            dataType: "json",
		            data: JSON.stringify({ productId: productId }),
		            success: function (data) {
		                // your code from above
		                alert(data.Text);
		                if (data.Value > 0) {
		                    window.location.reload(true);
		                } else if (data.Value) {

		                }
		            },
		            error: function (xhr, textStatus, error) {
		                console.log(xhr.statusText);
		                console.log(textStatus);
		                console.log(error);
		            }
		        });
		    }

		    function updateURLParameter(url, param, paramVal) {
		        var TheAnchor = null;
		        var newAdditionalURL = "";
		        var tempArray = url.split("?");
		        var baseURL = tempArray[0];
		        var additionalURL = tempArray[1];
		        var temp = "";

		        if (additionalURL) {
		            var tmpAnchor = additionalURL.split("#");
		            var TheParams = tmpAnchor[0];
		            TheAnchor = tmpAnchor[1];
		            if (TheAnchor)
		                additionalURL = TheParams;

		            tempArray = additionalURL.split("&");

		            for (var i = 0; i < tempArray.length; i++) {
		                if (tempArray[i].split('=')[0] != param) {
		                    newAdditionalURL += temp + tempArray[i];
		                    temp = "&";
		                }
		            }
		        }
		        else {
		            var tmpAnchor = baseURL.split("#");
		            var TheParams = tmpAnchor[0];
		            TheAnchor = tmpAnchor[1];

		            if (TheParams)
		                baseURL = TheParams;
		        }

		        if (TheAnchor)
		            paramVal += "#" + TheAnchor;
		        var rows_txt = temp + "" + param + "=" + paramVal;
		        return baseURL + "?" + newAdditionalURL + rows_txt;
		    }
		</script>
	</body>
</html>

MTD/Views/Shared/_PagingPartial.cshtml
<strong>Tổng số trang:</strong> <label style="color:red">@ViewBag.MaxPage</label>  <strong>Tổng số bản ghi:</strong> <label style="color:red"> @ViewBag.TotalRecord </label>

@if (ViewBag.MaxPage > 1)
{
    
    <ul class="pagination pull-right no-margin">
        @if (ViewBag.page > 1)
        {
        <!-- First page -->
            
        <li class="">
		    <a class="page" page-index='@(1)' href='#' class="btn btn-default">
                First
            </a>
	    </li>
        <!-- Preview page -->
        
        <li class="prev">
		    <a class="page" page-index='@(ViewBag.Page - 1)' href="#" class="btn btn-default">
                &laquo; Prev
            </a>
	    </li>    
        }

        <!-- Loop page -->
        @{
            int numPageShow = ViewBag.PageShow;
            int pageStart = 1;
            int pagePreview = ViewBag.PagePreview;
            int currPage = ViewBag.Page;
            int maxPage = ViewBag.MaxPage;
            if (maxPage < numPageShow)
            {
                numPageShow = maxPage;
                
                for (int i = 1; i <= numPageShow; i++)
                {
                    if (i == currPage) 
                    {
                        <li class="active">
                            <a>@i</a>
	                    </li>
                    }
                    else
                    {
                        <li class="">
		                    <a class="page"  page-index='@(i)' href="#" >
                               @i
                            </a>
	                    </li>
                    }

                }
            }
            else
            {
                // Tính trang bắt đầu hiển thị.

                if (currPage - 1 > pagePreview)
                {
                    if (maxPage - currPage >= pagePreview)
                    {
                        pageStart = currPage - pagePreview;
                    }
                    else
                    {
                        pageStart = maxPage - numPageShow + 1;
                    }
                }
                for (int j = pageStart; j < numPageShow + pageStart; j++)
                {
                    if (j == currPage)
                    {
                        <li class="active">
		                    <a>@j</a>
	                    </li>
                    }
                    else
                    {
                       <li class="">
		                <a class="page" page-index='@(j)' href="#" >
                           @j
                        </a>
	                </li>
                    }

                }
            }
        }

        <!-- Next page -->
        @if (ViewBag.page < ViewBag.MaxPage)
        {    
        <li class="next">
		    <a class="page" page-index='@(ViewBag.Page + 1)' href="#" 
               class="btn btn-default">
                Next &raquo;
            </a>
	    </li>        
        
        <!-- End page -->
	    <li>
		    <a class="page" page-index='@ViewBag.MaxPage' href="#" class="btn btn-default">
                End
            </a>
	    </li>
        }
    </ul>
}

<script type="text/javascript">
    $(".page").click(function () {
        var page = $(this).attr('page-index');
        var url = window.location.href;
        url = replaceUrlParam(url, "page", page);
        window.location.href = url;
    });

    function replaceUrlParam(url, paramName, paramValue) {
        if (paramValue == null) {
            paramValue = '';
        }
        var pattern = new RegExp('\\b(' + paramName + '=).*?(&|$)');
        if (url.search(pattern) >= 0) {
            return url.replace(pattern, '$1' + paramValue + '$2');
        }
        url = url.replace(/\?$/, '');
        return url + (url.indexOf('?') > 0 ? '&' : '?') + paramName + '=' + paramValue;
    }
</script>

MTD/Views/Shared/_PopupPartial.cshtml
@*To using: call @Html.Partial("_PopupPartial") in parent page
    And with anchor link, need add class modal-link
    Eg: @Html.ActionLink("Insert ", "RoleUpdate", "Admin", new { @id = 0 }, new { @class = "modal-link btn btn-primary" })
*@

@{
    Layout = null;
}

<div id="modal-container" class="modal fade" tabindex="-1">
    <div class="modal-content">
    </div>
</div>

<script type="text/javascript">
    $(function () {
        // Initialize numeric spinner input boxes
        //$(".numeric-spinner").spinedit();

        // Initalize modal dialog
        // attach modal-container bootstrap attributes to links with .modal-link class.
        // when a link is clicked with these attributes, bootstrap will display the href content in a modal dialog.
        $('body').on('click', '.modal-link', function (e) {
            e.preventDefault();
            $(this).attr('data-target', '#modal-container');
            $(this).attr('data-toggle', 'modal');
        });

        // Attach listener to .modal-close-btn's so that when the button is pressed the modal dialog disappears
        $('body').on('click', '.modal-close-btn', function () {
            $('#modal-container').modal('hide');
        });

        //clear modal cache, so that new content can be loaded
        $('#modal-container').on('hidden.bs.modal', function () {
            $(this).removeData('bs.modal');
        });

        $('#CancelModal').on('click', function () {
            return false;
        });
    });
</script>